version: '2'
services:
  backend:
    image: ${IMAGE_DEV}
    container_name: ${CONTAINER_NAME}
    ports:
      - "7501:7501"
    networks:
      default:
        aliases:
          - condopy-api

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}